version: '3'

services:
    php-apache:
        build:
            context: .
        container_name: php-apache
        expose:
            - 80
            - 443
        ports:
            - 8080:80
            - 443:443
